### PR TITLE
Departments

### PR DESCRIPTION
**Pull request by JordanRosas**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

HR is able to View a list of Departments and the size of the departments with an integer representing the number of employees in the department

HR is able to view details of a department and see the names of the employees in the department

HR is able to create a department set the budget, and  name

Fixes # (issue)
[Ticket #5] (https://github.com/nss-copper-dragonflies/WorkforceManagement/issues/5) , 
[Ticket #6} (https://github.com/nss-copper-dragonflies/WorkforceManagement/issues/6),
[Ticket #7] (https://github.com/nss-copper-dragonflies/WorkforceManagement/issues/7)
## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Testing Instructions
1. `git fetch --all`
2. `git checkout jr-Department`
3. run project
4.Navigate to Departments in the nav bar
5.Make sure the list of employees is present with the number of employees in the list
6.Click details make sure you can see a list of employees in the department 
7. Create a new department make sure the department is created and click details to view details of the newly added department

Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by ashwinp94 — APPROVED** [review]
great work!

**Review by bramosja — APPROVED** [review]
Everything is working =)

**Review by MissPeperr — CHANGES_REQUESTED** [review]
In your PR, please make sure you are properly linking the tickets using `[Ticket # 1](url-goes-here.com)`

**Comment by bramosja** [comment]
> In your PR, please make sure you are properly linking the tickets using `[Ticket # 1](url-goes-here.com)`

I didn't even know that was possible. Cool!

**Review by MissPeperr — APPROVED** [review]
👍 Looks good!

**Pull request merged**
